# Generated by Django 3.2.6 on 2021-08-19 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('brand_descr', models.TextField()),
                ('car_model', models.CharField(max_length=200)),
                ('model_descr', models.TextField()),
                ('year_of_manufacture', models.DateTimeField()),
                ('complectation', models.CharField(max_length=200)),
                ('complectation_descr', models.TextField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_portal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
